import type { Config } from 'tailwindcss';

export default {
  content: ['./src/**/*.{tsx,ts,jsx,js}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        outline: '#849495',
        'inverse-primary': '#006970',
        'on-surface-variant': '#b9cacb',
        'surface-bright': '#3a393a',
        'surface-container': '#201f20',
        'error-container': '#93000a',
        'secondary-fixed-dim': '#d0bcff',
        'on-background': '#e5e2e3',
        'outline-variant': '#3b494b',
        secondary: '#d0bcff',
        tertiary: '#fff5de',
        'surface-dim': '#131314',
        'surface-tint': '#00dbe9',
        'inverse-on-surface': '#313031',
        error: '#ffb4ab',
        'primary-fixed': '#7df4ff',
        'on-secondary': '#3c0091',
        'on-primary': '#00363a',
        'on-error-container': '#ffdad6',
        background: '#131314',
        'surface-container-highest': '#353436',
        'secondary-container': '#571bc1',
        'surface-container-low': '#1c1b1c',
        surface: '#131314',
        'on-secondary-container': '#c4abff',
        'on-surface': '#e5e2e3',
        'on-error': '#690005',
        'surface-container-lowest': '#0e0e0f',
        'primary-fixed-dim': '#00dbe9',
        'on-primary-container': '#006970',
        'primary-container': '#00f0ff',
        primary: '#dbfcff',
        'inverse-surface': '#e5e2e3',
        'surface-container-high': '#2a2a2b',
        'surface-variant': '#353436',
        'secondary-fixed': '#e9ddff',
        'tertiary-container': '#fed639',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
} satisfies Config;
