import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

interface RepositoryScaffoldContext {
  safeName: string;
  displayName: string;
  owner: string;
  projectType: 'single-app' | 'monorepo';
  buildCommand: string;
  unitTestCommand: string;
  docsValidationCommand: string;
  hasReadme: boolean;
  hasDocsDir: boolean;
  hasSchemasDir: boolean;
  hasCliDir: boolean;
  hasAgentsDoc: boolean;
  hasCopilotInstructions: boolean;
  hasArchitectureDoc: boolean;
  hasStructureDoc: boolean;
}

// Resolve Spec2Flow's own root directory from this module's location.
// dist layout: packages/cli/dist/shared/scaffold-spec2flow.js → 4 levels up = root
function getSpec2flowRoot(): string {
  const thisFile = fileURLToPath(import.meta.url);
  return path.resolve(path.dirname(thisFile), '..', '..', '..', '..');
}

/**
 * Writes minimal .spec2flow scaffold files into a project directory.
 * Always overwrites YAML files that contain the auto-generated marker.
 * Writes model-adapter-runtime.json only if absent (preserves user edits).
 */
export function scaffoldSpec2flowFiles(
  repositoryRootPath: string,
  projectName: string,
  projectPath = '.spec2flow/project.yaml',
  topologyPath = '.spec2flow/topology.yaml',
  riskPath = '.spec2flow/policies/risk.yaml'
): void {
  const resolve = (rel: string): string => path.resolve(repositoryRootPath, rel);
  const safeName = projectName
    .trim()
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/g, '-')
    .replaceAll(/^-+|-+$/g, '') || 'project';
  const scaffoldContext = inferRepositoryScaffoldContext(repositoryRootPath, safeName, projectName);

  writeIfMissingOrAutoGenerated(resolve(projectPath), buildProjectYaml(scaffoldContext));
  writeIfMissingOrAutoGenerated(resolve(topologyPath), buildTopologyYaml(scaffoldContext));
  writeIfMissingOrAutoGenerated(resolve(riskPath), buildRiskYaml());
  // Adapter runtime: write only if absent so user edits are never overwritten.
  writeIfMissing(resolve('.spec2flow/model-adapter-runtime.json'), buildAdapterRuntimeJson(getSpec2flowRoot()));
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function readPackageJson(repositoryRootPath: string): Record<string, unknown> | null {
  const packageJsonPath = path.join(repositoryRootPath, 'package.json');
  if (!fs.existsSync(packageJsonPath)) {
    return null;
  }

  try {
    const payload = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8')) as unknown;
    return isRecord(payload) ? payload : null;
  } catch {
    return null;
  }
}

function readStringMap(value: unknown): Record<string, string> {
  if (!isRecord(value)) {
    return {};
  }

  return Object.fromEntries(
    Object.entries(value)
      .filter((entry): entry is [string, string] => typeof entry[1] === 'string')
  );
}

function readStringValue(source: Record<string, unknown> | null, key: string): string | null {
  const value = source?.[key];
  return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null;
}

function hasWorkspaceConfig(packageJson: Record<string, unknown> | null): boolean {
  const workspaces = packageJson?.workspaces;
  return Array.isArray(workspaces)
    || (isRecord(workspaces) && Array.isArray(workspaces.packages));
}

function pathExists(repositoryRootPath: string, relativePath: string): boolean {
  return fs.existsSync(path.join(repositoryRootPath, relativePath));
}

function inferProjectOwner(packageJson: Record<string, unknown> | null, safeName: string): string {
  const packageName = readStringValue(packageJson, 'name');
  if (!packageName) {
    return safeName;
  }

  if (packageName.startsWith('@')) {
    const scopedOwner = packageName.slice(1).split('/')[0];
    return scopedOwner || safeName;
  }

  return safeName;
}

function inferRepositoryScaffoldContext(
  repositoryRootPath: string,
  safeName: string,
  displayName: string
): RepositoryScaffoldContext {
  const packageJson = readPackageJson(repositoryRootPath);
  const scripts = readStringMap(packageJson?.scripts);
  const hasDocsDir = pathExists(repositoryRootPath, 'docs');
  const hasSchemasDir = pathExists(repositoryRootPath, 'schemas');
  const hasCliDir = pathExists(repositoryRootPath, path.join('packages', 'cli'));
  const isMonorepo = hasWorkspaceConfig(packageJson) || (hasCliDir && (hasDocsDir || hasSchemasDir));

  return {
    safeName,
    displayName,
    owner: inferProjectOwner(packageJson, safeName),
    projectType: isMonorepo ? 'monorepo' : 'single-app',
    buildCommand: scripts.build ? 'npm run build' : 'echo "build"',
    unitTestCommand: scripts['test:unit'] ? 'npm run test:unit' : scripts.test ? 'npm test' : 'echo "ok"',
    docsValidationCommand: scripts['validate:docs'] ? 'npm run validate:docs' : 'echo "ok"',
    hasReadme: pathExists(repositoryRootPath, 'README.md'),
    hasDocsDir,
    hasSchemasDir,
    hasCliDir,
    hasAgentsDoc: pathExists(repositoryRootPath, 'AGENTS.md'),
    hasCopilotInstructions: pathExists(repositoryRootPath, path.join('.github', 'copilot-instructions.md')),
    hasArchitectureDoc: pathExists(repositoryRootPath, path.join('docs', 'architecture.md')),
    hasStructureDoc: pathExists(repositoryRootPath, path.join('docs', 'structure.md')),
  };
}

function writeIfMissing(absolutePath: string, content: string): void {
  if (fs.existsSync(absolutePath)) return;
  fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
  fs.writeFileSync(absolutePath, content, 'utf8');
}

function writeIfMissingOrAutoGenerated(absolutePath: string, content: string): void {
  if (fs.existsSync(absolutePath)) {
    // Only overwrite files that were auto-generated by Spec2Flow (safe to refresh).
    // Leave hand-authored files untouched.
    const existing = fs.readFileSync(absolutePath, 'utf8');
    if (!existing.includes('Auto-generated by Spec2Flow')) {
      return;
    }
  }
  fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
  fs.writeFileSync(absolutePath, content, 'utf8');
}

function renderYamlWithFooter(document: unknown, footerLines: string[]): string {
  const yamlContent = yaml.dump(document, {
    lineWidth: -1,
    noRefs: true,
    sortKeys: false,
  }).trimEnd();
  return `${yamlContent}\n\n${footerLines.join('\n')}\n`;
}

function buildProjectYaml(context: RepositoryScaffoldContext): string {
  if (context.projectType === 'monorepo' && context.hasCliDir) {
    const requirementDocs = [
      ...(context.hasReadme ? ['README.md'] : []),
      ...(context.hasDocsDir ? ['docs/index.md', 'docs/usage-guide.md'] : []),
    ];
    const architectureDocs = [
      ...(context.hasAgentsDoc ? ['AGENTS.md'] : []),
      ...(context.hasCopilotInstructions ? ['.github/copilot-instructions.md'] : []),
      ...(context.hasArchitectureDoc ? ['docs/architecture.md'] : []),
      ...(context.hasStructureDoc ? ['docs/structure.md'] : []),
    ];

    const services: Record<string, unknown> = {
      cli: {
        path: 'packages/cli',
        type: 'backend',
        start: context.buildCommand,
        test: context.unitTestCommand,
      },
    };

    if (context.hasDocsDir) {
      services.docs = {
        path: 'docs',
        type: 'other',
        start: context.docsValidationCommand,
        test: context.docsValidationCommand,
        dependsOn: ['cli'],
      };
    }

    if (context.hasSchemasDir) {
      services.schemas = {
        path: 'schemas',
        type: 'other',
        start: context.buildCommand,
        test: context.buildCommand,
        dependsOn: ['cli'],
      };
    }

    return renderYamlWithFooter({
      spec2flow: {
        project: {
          name: context.safeName,
          type: 'monorepo',
          defaultBranch: 'main',
          owner: context.owner,
        },
        docs: {
          requirements: requirementDocs,
          architecture: architectureDocs,
        },
        services,
        infrastructure: {
          bootstrap: context.buildCommand,
        },
        tests: {
          build: context.buildCommand,
          unit: context.unitTestCommand,
          ...(context.hasDocsDir ? { docs: context.docsValidationCommand } : {}),
        },
        artifacts: {
          baseDir: '.spec2flow/generated',
          executionDir: '.spec2flow/generated/execution',
          bugsDir: '.spec2flow/generated/bugs',
        },
      },
    }, [
      `# Auto-generated by Spec2Flow for project: ${context.displayName}`,
      '# Review the inferred services, docs, and commands before production use.',
    ]);
  }

  return renderYamlWithFooter({
    spec2flow: {
      project: {
        name: context.safeName,
        type: 'single-app',
        defaultBranch: 'main',
        owner: context.owner,
      },
      docs: {
        requirements: context.hasReadme ? ['README.md'] : [],
        architecture: context.hasReadme ? ['README.md'] : [],
      },
      services: {
        app: {
          path: '.',
          type: 'backend',
          start: 'echo "ready"',
          test: 'echo "ok"',
        },
      },
      infrastructure: {
        bootstrap: 'echo "bootstrap"',
      },
      tests: {
        build: context.buildCommand,
      },
      artifacts: {
        baseDir: '.spec2flow/generated',
        executionDir: '.spec2flow/generated/execution',
        bugsDir: '.spec2flow/generated/bugs',
      },
    },
  }, [
    `# Auto-generated by Spec2Flow for project: ${context.displayName}`,
    '# Customise start/test commands to match your actual build toolchain.',
  ]);
}

function buildTopologyYaml(context: RepositoryScaffoldContext): string {
  if (context.projectType === 'monorepo' && context.hasCliDir) {
    const services: Array<Record<string, unknown>> = [
      {
        name: 'cli',
        kind: 'backend',
        critical: true,
        healthChecks: [{
          type: 'command',
          target: context.buildCommand,
          timeoutSeconds: 120,
        }],
      },
    ];
    const startupOrder = ['cli'];
    const workflowRoutes: Array<Record<string, unknown>> = [];

    if (context.hasDocsDir) {
      services.push({
        name: 'docs',
        kind: 'other',
        dependsOn: ['cli'],
        healthChecks: [{
          type: 'command',
          target: context.docsValidationCommand,
          timeoutSeconds: 120,
        }],
      });
      startupOrder.push('docs');
      workflowRoutes.push({
        name: 'docs-governance',
        entryServices: ['docs', 'cli'],
        verifyCommands: [context.buildCommand, context.unitTestCommand, context.docsValidationCommand],
        artifactTargets: ['.spec2flow/generated/execution/docs-governance'],
        requirementSignals: {
          summary: 'Documentation governance, navigation, and validator changes.',
          keywords: ['docs', 'documentation', 'validate:docs', 'validator', 'architecture', 'usage', 'index', '文档', '校验'],
          phrases: ['docs governance', 'documentation cleanup', 'validate docs', 'docs validator', '文档治理'],
        },
      });
    }

    workflowRoutes.push({
      name: 'cli-runtime',
      entryServices: ['cli'],
      verifyCommands: [context.buildCommand, context.unitTestCommand],
      artifactTargets: ['.spec2flow/generated/execution/cli-runtime'],
      requirementSignals: {
        summary: 'CLI runtime, workflow loop, and adapter execution changes.',
        keywords: ['cli', 'runtime', 'workflow', 'adapter', 'task graph', 'execution state', '命令行', '运行时'],
        phrases: ['workflow loop', 'execution state', 'task graph', 'cli runtime'],
      },
    });

    if (context.hasSchemasDir) {
      services.push({
        name: 'schemas',
        kind: 'other',
        dependsOn: ['cli'],
        healthChecks: [{
          type: 'command',
          target: context.buildCommand,
          timeoutSeconds: 120,
        }],
      });
      startupOrder.push('schemas');
      workflowRoutes.push({
        name: 'schema-contracts',
        entryServices: ['schemas', 'cli'],
        verifyCommands: [context.buildCommand, context.unitTestCommand],
        artifactTargets: ['.spec2flow/generated/execution/schema-contracts'],
        requirementSignals: {
          summary: 'Schema, contract, and type-alignment changes.',
          keywords: ['schema', 'contract', 'type', 'validation', 'json schema', '契约', '类型'],
          phrases: ['schema contract', 'contract alignment', 'json schema'],
        },
      });
    }

    return renderYamlWithFooter({
      topology: {
        services,
        startupOrder,
        workflowRoutes,
      },
    }, [
      '# Auto-generated by Spec2Flow. Customise services and routes to match your project.',
    ]);
  }

  return renderYamlWithFooter({
    topology: {
      services: [{
        name: 'app',
        kind: 'backend',
        critical: true,
        healthChecks: [{
          type: 'command',
          target: 'echo "ok"',
          timeoutSeconds: 30,
        }],
      }],
      startupOrder: ['app'],
      workflowRoutes: [{
        name: 'default',
        entryServices: ['app'],
        verifyCommands: ['echo "verify"'],
        artifactTargets: ['.spec2flow/generated/execution/default'],
        requirementSignals: {
          summary: `Default delivery route for ${context.safeName}.`,
          keywords: ['feature', 'fix', 'implement', 'build'],
        },
      }],
    },
  }, [
    '# Auto-generated by Spec2Flow. Customise services and routes to match your project.',
  ]);
}

function buildRiskYaml(): string {
  return `riskPolicy:
  defaultLevel: execute-to-pr

  automationLevels:
    - name: l0-assist
      description: analyze only
      maxAutonomy: analysis-only

    - name: l1-controlled
      description: implement and validate
      maxAutonomy: execute-to-pr

  rules:
    - name: default-low-risk
      level: low
      match:
        paths:
          - "**/*"
      requires:
        humanApproval: false
        reviewAgents: 1
        mustRunCommands: []
      blockAutoMerge: false

# Auto-generated by Spec2Flow. Tighten rules to match your risk tolerance.
`;
}

function buildAdapterRuntimeJson(spec2flowRoot: string): string {
  const adapterScript = path.join(spec2flowRoot, 'docs', 'examples', 'synapse-network', 'example-command-adapter.mjs');
  return JSON.stringify(
    {
      adapterRuntime: {
        name: 'spec2flow-copilot-cli-adapter',
        provider: 'github-copilot-cli',
        command: 'node',
        args: [adapterScript, '--claim', '${claimPath}'],
        cwd: spec2flowRoot,
        env: {
          SPEC2FLOW_COPILOT_CWD: spec2flowRoot,
          SPEC2FLOW_COPILOT_SESSION_KEY: '${specialistSessionKey}',
          SPEC2FLOW_COPILOT_SESSION_DIR: '.spec2flow/runtime/copilot-sessions',
          SPEC2FLOW_STATE: '${statePath}',
          SPEC2FLOW_TASK_GRAPH: '${taskGraphPath}',
          SPEC2FLOW_TASK_ID: '${taskId}',
          SPEC2FLOW_RUN_ID: '${runId}',
          SPEC2FLOW_ALLOW_FILE_WRITES: 'true',
          SPEC2FLOW_ALLOW_TEST_RUNS: 'true',
          SPEC2FLOW_ALLOW_GIT_WRITE: 'false',
          SPEC2FLOW_ALLOW_PR_CREATE: 'false'
        },
        timeoutMs: 600000,
        outputMode: 'stdout'
      }
    },
    null,
    2
  ) + '\n';
}
