ALTER TABLE __SPEC2FLOW_SCHEMA__.tasks
  ADD COLUMN IF NOT EXISTS retry_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE __SPEC2FLOW_SCHEMA__.tasks
  ADD COLUMN IF NOT EXISTS max_retries INTEGER NOT NULL DEFAULT 3;

ALTER TABLE __SPEC2FLOW_SCHEMA__.tasks
  ADD COLUMN IF NOT EXISTS leased_by_worker_id TEXT;

ALTER TABLE __SPEC2FLOW_SCHEMA__.tasks
  ADD COLUMN IF NOT EXISTS lease_expires_at TIMESTAMPTZ;

ALTER TABLE __SPEC2FLOW_SCHEMA__.tasks
  ADD COLUMN IF NOT EXISTS last_heartbeat_at TIMESTAMPTZ;

ALTER TABLE __SPEC2FLOW_SCHEMA__.task_attempts
  ADD COLUMN IF NOT EXISTS leased_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE __SPEC2FLOW_SCHEMA__.task_attempts
  ADD COLUMN IF NOT EXISTS last_heartbeat_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS spec2flow_tasks_lease_expiry_idx
  ON __SPEC2FLOW_SCHEMA__.tasks (status, lease_expires_at);
